server:
  port: 8080  # 포트 8080으로 설정
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  # JSP 설정
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/board  # MySQL 데이터베이스 URL
    username: root  # MySQL 사용자명
    password: 1234  # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 설정
    hikari:
      maximum-pool-size: 10  # 데이터베이스 연결 풀 크기 (선택 사항)

  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성/업데이트 전략 (none, update, create, create-drop 등)
    show-sql: true  # SQL 쿼리를 로그에 출력
    open-in-view: false

  # Thymeleaf를 비활성화 (JSP 사용을 위해)
  thymeleaf:
    enabled: false

logging:
  level:
    org.springframework.web: DEBUG  # 디버깅을 위해 Spring 웹 관련 로그 레벨을 DEBUG로 설정 (선택 사항)